apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: salamy1/ping-pong:v0.4.6
          envFrom:
            - configMapRef:
                name: pg-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: pg-password
                    key: POSTGRES_PASSWORD
          # volumeMounts:
          #   - name: shared-log-output
          #     mountPath: /usr/src/app/files
      # volumes:
      #   - name: shared-log-output
      #     persistentVolumeClaim:
      #       claimName: log-output-claim