apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: salamy1/ping-pong:v0.6
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
          envFrom:
            - configMapRef:
                name: pg-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-password
                  key: POSTGRES_PASSWORD
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
