apiVersion: v1
kind: Secret
metadata:
    namespace: apps
    name: pg-password
data:
    #ENC[AES256_GCM,data:tcmfN8LHRVAiIWVKazJMRA==,iv:WxWeQdMFLxxCW9OIiMt3S8E3lchCprsWoNt8v6wxQZg=,tag:rBAvjaMdsqTRPjUwOuNN9w==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1TiEAm1lnqjtgfpV4Qzwvr1LkOJbtg==,iv:BCF7jIKliWscklJSo1OxpBTPwkjpKS9YA9TMvZDu1So=,tag:7DZgDXaHoas4sydESYMmAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pd3h9c79x30g3ej7qdh3ehdw7fypyyx46tahxck4xpz99xc8s7s0zgee2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZk9LKzF0UWJhZlBrUzdt
            a1BXRVVjVllxRk5aUTZRVXdrbXN5cUlzSnkwCkZYc04rL1MxZEo5WnRkZ0N2bXdp
            N0lVNUlZdUoxN3dlWnNoUXYzSG5Zc2cKLS0tIEJKVU9zZGdNdVlIdmZDZi9Kc3dM
            aEg0SHZiV0VxVlF2RlAxdUREK29DUDAKOGbKmDJDlzB1JhV8fKqhhpTBJdvhR/S/
            KW2fs55P4xsMgNIIS3GXccrpEHqMP/uFjirulxKlwlVUOUGp3WoOXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-24T20:17:36Z"
    mac: ENC[AES256_GCM,data:i/Ehh0/hVUGu6gMpyYrBzhhQDVSF9pcZID/VrZ0hJFdqw9665SFiLpPgmHNCAVOYcyxMsCT7Pm7u1LdEVBMrXlwlplPyM7LwwJjFusYKCb14l7szDr/e9E3tdLAlLCCme7Biq0FbMP6hYSxlhLw57JtKKG4EE1tzUF61eRtwhzw=,iv:c0rHZL+lJV57O371GUrZCEl+EwL10qhAbcI3v2544ug=,tag:To0Uc9qT2lvU+EOwWjyjzg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.1
