apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: broadcaster
    spec:
      containers:
        - env:
            - name: NATS_URL
              value: nats://my-nats.default:4222
            - name: TG_CHAT_ID
              value: "@dwkreceiver"
            - name: TG_TOKEN
              valueFrom:
                secretKeyRef:
                  key: TG_TOKEN
                  name: telegram-secret
          image: salamy1/project-broadcaster:v1.3
          name: broadcaster
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
