apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - manifests/namespace.yaml
  - manifests/secret.yaml
  - manifests/statefulset.yaml
  - manifests/configmap.yaml
  - manifests/rollout.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/persistentvolume.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/hpa.yaml
  - manifests/cron.yaml
  - manifests/analysistemplate.yaml
images:
  - name: project/api
    newName: salamy1/project-api:v1.8.3
  - name: project/client
    newName: salamy1/project-client:v1.8.1
