apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-rate
  namespace: project
spec:
  metrics:
    - name: cpu-rate
      initialDelay: 10m
      successCondition: result < 0.015
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1638-prometheus.prometheus.svc.cluster.local:9090 # DNS name for my Prometheus, find yours with kubectl describe svc ...
          query: |
            scalar(sum(rate(container_cpu_usage_seconds_total{namespace="project", container="kube-project-api"}[10m])))
