apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: daily-todo
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-todo
            image: salamy1/deno-cron:v1.3
            env:
              - name: uri
                value: "http://kube-project-svc:2345/api/todos"
          restartPolicy: Never # This time we'll run it only once