apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-todo
  namespace: project
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            linkerd.io/inject: enabled
        spec:
          containers:
            - env:
                - name: uri
                  value: http://kube-project-svc:2345/api/todos
              image: salamy1/deno-cron:v1.3
              name: daily-todo
          restartPolicy: Never
  schedule: "@daily"
