apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-project
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: kube-project
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: pg-password
            - name: NATS_URL
              value: nats://my-nats.default:4222
          envFrom:
            - configMapRef:
                name: pg-config
          image: project/api
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
          name: kube-project-api
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: random-image
        - image: project/client
          name: kube-project-client
          resources:
            limits:
              cpu: 300m
              memory: 700Mi
      volumes:
        - name: random-image
          persistentVolumeClaim:
            claimName: project-claim
