apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-project-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: kube-project-svc
                port:
                  number: 2345