apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
  # - rollout.yaml
resources:
- namespace.yaml
- secret.enc.yaml
- statefulset.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- cron.yaml
- analysistemplate.yaml
images:
- name: project/api
  newName: salamy1/project-api
  newTag: 27b58e57a98308c621e1cf36f58dbbe75fda1dbc
- name: project/client
  newName: salamy1/project-client
  newTag: 27b58e57a98308c621e1cf36f58dbbe75fda1dbc
