apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output-reader
          image: salamy1/log-reader:v0.1.8
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-log-output
        - name: log-output-writer
          image: salamy1/log-writer:v0.1
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-log-output
      volumes:
        - name: shared-log-output
          persistentVolumeClaim:
            claimName: log-output-claim