apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      namespace: apps
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output-reader
          image: salamy1/log-reader:v0.3
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-log-output
          env:
              - name: MESSAGE
                valueFrom:
                    configMapKeyRef:
                      name: app-config
                      key: message
        - name: log-output-writer
          image: salamy1/log-writer:v0.3
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-log-output
          
      volumes:
        - name: shared-log-output
          persistentVolumeClaim:
            claimName: log-output-claim
      